### ISSUE TITLE
備註送出無效

### ISSUE THREAD

**Issue by Chun-Cheng** [utaipei-sa/reserve.utsa#59]
於新增預約紀錄或編輯預約紀錄頁面，輸入或編輯備註內容，送出後無法被正常儲存。

尚未確定問題出在前端還是後端。

![Screenshot_20241123_010525_Arc Search](https://uploads.linear.app/d67ebed9-d048-4ea0-aab0-f2825d41d4ad/8e5c5008-0e87-4ba2-9379-8153985d448f/52b9feca-f7ac-4f24-82a9-0027d66689be?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Q2N2ViZWQ5LWQwNDgtNGVhMC1hYWIwLWYyODI1ZDQxZDRhZC84ZTVjNTAwOC0wZTg3LTRiYTItOTM3OS04MTUzOTg1ZDQ0OGYvNTJiOWZlY2EtZjdhYy00ZjI0LTgyYTktMDAyN2Q2NjY4OWJlIiwiaWF0IjoxNzMyMjk2MzAzLCJleHAiOjMzMzAyODU2MzAzfQ.7aLPfyRG9EylxcQOk1XVg53IZ4BMJO7G2DWeaksG_9s "=1079x")

<img src="https://uploads.linear.app/d67ebed9-d048-4ea0-aab0-f2825d41d4ad/e9e865c7-0c02-4aab-9a0e-001ae7413a08/d617647e-9ace-44cb-acc1-83f756eeb539?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Q2N2ViZWQ5LWQwNDgtNGVhMC1hYWIwLWYyODI1ZDQxZDRhZC9lOWU4NjVjNy0wYzAyLTRhYWItOWEwZS0wMDFhZTc0MTNhMDgvZDYxNzY0N2UtOWFjZS00NGNiLWFjYzEtODNmNzU2ZWViNTM5IiwiaWF0IjoxNzMyMjk2MzA5LCJleHAiOjMzMzAyODU2MzA5fQ.P8tjvCW00_TrOy2R40XnHs0GlZbIw1J36uHURMTfdpg " alt="Screenshot_20241123_010557_Gmail\~3.jpg" width="1079" height="1808" />

**Comment by marvelcn015** [comment]
初步確定應該是後端的問題，目前正在尋找問題中!

**Comment by BlueBoy247** [comment]
但我剛剛看感覺是前端的問題？確認框備註用的是`props.submit_data.note`，但script裡`submit.value`用的是`submit_data.note`，改成確認框用的值之後測試有正常

**Comment by marvelcn015** [comment]
已修正前端問題，感謝協助!
