### ISSUE TITLE
使用Vuetify的table元件取代自製的表格

### ISSUE THREAD

**Issue by nickchengtw** [utaipei-sa/reserve.utsa#6]
使用 Vuetify 的 table 元件取代 ItemDisplay.vue & SpaceDisplay.vue 自製的表格
https://vuetifyjs.com/en/components/tables/

_Originally posted by @nickchengtw in https://github.com/utaipei-sa/reserve.utsa/pull/5#discussion_r1654879033_

**Comment by Jeff92316046** [comment]
我已經commit在原本那支pr上了😂
